### ISSUE TITLE
Could you please kindly offer guidance how can I change the model in the mod , I have encountered some trouble

### ISSUE THREAD

**Issue by TShineCN** [qqrz997/LethalCompany_KoishiGhost#1]
Thank you very much for creating this mod! Could you please spare some time to kindly offer some guidance? If you are not willing to answer, I am also very grateful to you.

I uesd assetbundle browser ,tried to building my own assets (model and audio) in Unity, and the audio could be replaced, but the girl's model completely disappeared and became invisible.

I would like to know how you building assets. I converted an FBX model to prefab format, and the prefab format was a mesh(named Body) and a bone(named metarig), with a .mat Material. The bone binding is the same as the model bone in your mod. After building assets, there will be no error when running in the game, but I can't see the model. I tried for a long time and didn't understand what the problem was.

**Comment by qqrz997** [comment]
[This is the unity project](https://github.com/EvaisaDev/LethalCompanyUnityTemplate) that has the HDRP shaders that you need for your renderer to show in game. The Girl uses HDRP Unlit by default

**Comment by TShineCN** [comment]
> [This is the unity project](https://github.com/EvaisaDev/LethalCompanyUnityTemplate) that has the HDRP shaders that you need for your renderer to show in game. The Girl uses HDRP Unlit by default

WOW,cool! Thank you very much!  I will try it.

**Comment by TShineCN** [comment]
> [This is the unity project](https://github.com/EvaisaDev/LethalCompanyUnityTemplate) that has the HDRP shaders that you need for your renderer to show in game. The Girl uses HDRP Unlit by default

Thank you again for your answer! I have resolved the issue of not being able to render, thank you very much!
