### ISSUE TITLE
Model rendering issues

### ISSUE THREAD

**Issue by TShineCN** [qqrz997/LethalCompany_KoishiGhost#2]
Hello, I seem to have found a rendering issue while testing your mod.The girl stared at a player and ran away. The vanilla game logic was to become invisible and cancel the collision kill, but the model was still in the place where the girl gone. In multiplayer games, the person who is chased by the girl while the girl is invisible cannot see the model, but everyone else can see the girl's model.

**Comment by TShineCN** [comment]
I feel like there's a problem with the 【skinnedMeshRenderer】 settings. I think it should have set the rendering layer using the original game's【EnableEnemyMesh】 method, I tried but failed. Maybe it's because I wrote the code incorrectly, or maybe there's a problem with the prefab setting in Unity

**Comment by TShineCN** [comment]
I added this line to code, then I found can render according to the original logic
【bodyMesh.gameObject.layer = LayerMask.NameToLayer("EnemiesNotRendered");】

**Comment by KivalEvan** [comment]
i'll look into it soon, strange that happened

**Comment by qqrz997** [comment]
this seems to be fixed in the [latest](https://github.com/qqrz997/LethalCompany_KoishiGhost/releases/latest), but if someone encounters this issue again this can be reopened
