### ISSUE TITLE
A question about animation

### ISSUE THREAD

**Issue by TShineCN** [qqrz997/LethalCompany_KoishiGhost#3]
Could you please spare some time to kindly offer some guidance?
I successfully replaced the enemy's model by disabling the original enemy's skinnemeshrender and then loading my own skinnemeshrenderer. But I found that there are significant issues with the enemy's animation, the leg animation(thigh shin) is completely reversed 180 degrees. I have no idea where the problem lies now. The bone weights, orientation, and animation in Blender and Unity are all fine,I don't know how to solve this problem.

**Comment by KivalEvan** [comment]
hey, i don't have a clear answer and my assumption is that you have your model facing 180 degree away from actual front (you may try to rotate them to fix it, either in blender or unity) or bone name assigned wrongly
personally, i have not run into this issue to know the solution

edit: i should add that, from experience, bone hierarchy matter if your animation still remain stiff (has to match original bone model) but i don't exactly know if there are better ways

if you wish to have further support, you should check out [Lethal Company Modding Discord](https://discord.gg/XeyYqRdRGC) as they can provide you with more information
github issue should only be used to report issue regarding the mod
