### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by letmepickausernamedammit** [qqrz997/LethalCompany_KoishiGhost#4]
It just doesn't work, straight up. Has the mod been abandoned? Whenever my group has encountered the ghost girl, it has only ever used the vanilla model, which is disappointing honestly.

**Comment by qqrz997** [comment]
The game hasn't recieved any updates. Without any description I cannot help you with your installation. Visit the lethal company modding [discord](https://discord.com/invite/XeyYqRdRGC) for help with installing mods. It's also possible you have another mod that collides with this, if there is another mod related to the ghost girl.

**Comment by letmepickausernamedammit** [comment]
Okay, so basically the mod doesn't do what it promises to do. I've installed it with thunderstore like I would with any other mod, I've even tried running the mod standalone. Despite this, it doesn't change the ghost girl's model. I don't know how to explain it any further than "straight up doesn't do anything to the game."

**Comment by qqrz997** [comment]
please send your logs file from \r2modmanPlus-local\LethalCompany\profiles\<YourProfileName>\BepInEx
